### ISSUE TITLE
detect corrupt map

### ISSUE THREAD

**Issue by ImanCol** [REDxEYE/SourceIO#306]
Is it possible that corrupt maps can be detected in the compilation before running the game to test it? I found that using func_areaportalwindow or func_areaportal can generate errors if the borders are not closed correctly

**Comment by REDxEYE** [comment]
SourceIO cannot do that

**Comment by treacherousfiend** [comment]
As a side note: the map compilers already do this, you don't need any external tools to know if there is an issue with your map before opening it in 99% of scenarios. In this case, during the VBSP stage if this error occurs you will see a message such as:
```
**** leaked ****
Entity func_areaportal (-1607.69 -1094.12 -183.00) leaked!
```

I also would recommend adding `-leaktest` to your VBSP options, as it will stop your compile when you have a leak rather than continuing.

**Comment by ImanCol** [comment]
error, this is for hammer++.  But I didn't realize that they don't have a repo.

**Comment by ImanCol** [comment]
> As a side note: the map compilers already do this, you don't need any external tools to know if there is an issue with your map before opening it in 99% of scenarios. In this case, during the VBSP stage if this error occurs you will see a message such as:
> 
> ```
> **** leaked ****
> Entity func_areaportal (-1607.69 -1094.12 -183.00) leaked!
> ```
> 
> I also would recommend adding `-leaktest` to your VBSP options, as it will stop your compile when you have a leak rather than continuing.

This is not an error about whether an object is out of bounds.   It is a func_areaportal error that I saw was in a door that opens, not having the door frames correctly.   I think it is used to not transfer light or objects to the other side when moving away (black blur) and requires that its edges have some wall.  If it is not correct, it will crash when loading the map (the compiler does not detect this error and compiles the map and runs the game, but it will crash)

**Comment by treacherousfiend** [comment]
That is still a leak, areaportals must be completely sealed, although i've never heard of it causing a crash. Regardless, you're correct that this is not the right repo for this, although it is unlikely to be a hammer++ issue as 99% of the data it saves is identical to that of regular hammer.

**Comment by ImanCol** [comment]
I don't know if it's okay to continue the conversation. I still have this error. It happens when I instantiate my door mechanism to open 2 times. (if I instantiate it once it works fine)

[GSteamLibrarysteamappscommonLeft 4 Dead 2binhammerplusplusbinhammerplusplus_compiler.exe.txt](https://github.com/user-attachments/files/16273960/GSteamLibrarysteamappscommonLeft.4.Dead.2binhammerplusplusbinhammerplusplus_compiler.exe.txt)

![image](https://github.com/user-attachments/assets/d6629a1a-3b4d-4410-9892-8bd319049a8f)

[opendoor3_L4D2_Inscanse.zip](https://github.com/user-attachments/files/16273903/opendoor3_L4D2_Inscanse.zip)

**Comment by treacherousfiend** [comment]
> error, this is for hammer++. But I didn't realize that they don't have a repo.

I just realized I misread this message and thought you already knew they had a repo.
https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/issues
Its not _really_ active anymore since the issue tracker is deprecated but it might be better than this repo.
A better idea I think would be to look into mapping communities for your game (either on discord or elsewhere), they probably would be much better suited to help you than we are.

Regardless, just looking at the compile log these errors might be a good place to start debugging. I'm not sure why it would cause the map to become corrupted but its the only thing out of place I can see.
![image](https://github.com/user-attachments/assets/b40931b8-a169-4447-9076-7262d0a43132)
